# Generated by Django 4.1.4 on 2022-12-25 17:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.TextField(max_length=100)),
                ('text', tinymce.models.HTMLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
