# Generated by Django 4.1.4 on 2022-12-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDate',
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
